export const continents = [
  {
    id : 0,
    name : 'Asia',
    lat : 99.5,
    long : 33,
    description : 'Asia is the largest continent, covering a diverse range of cultures, landscapes, and peoples. From the vast steppes of Central Asia to the bustling metropolises of China and India, Asia is home to a rich tapestry of history and traditions. The continent is known for its economic powerhouses, technological innovations, and ancient civilizations, making it a pivotal player in global affairs.',
  },
  {
    id : 1,
    name : 'Africa',
    lat : 37.4,
    long : 19.1,
    description : 'Africa, the second-largest continent, is renowned for its stunning biodiversity, unique wildlife, and varied landscapes. From the Sahara Desert in the north to the lush rainforests of Central Africa, the continent is a mosaic of ecosystems. Africa has a rich history, marked by ancient civilizations like Egypt, and a vibrant cultural heritage that encompasses a multitude of languages, traditions, and music.',
  },
  {
    id : 2,
    name : 'Antartica',
    lat : 0,
    long : -89.5,
    description : 'Antarctica, the southernmost continent, is a vast, icy wilderness that remains largely uninhabited. It is characterized by stunning landscapes, including towering glaciers and the Antarctic Peninsula. While devoid of a permanent human population, Antarctica is crucial for scientific research, with numerous research stations studying climate change and the unique ecosystems that thrive in extreme conditions.',
  },
  {
    id : 3,
    name : 'South America',
    lat : 14.8048,
    long : 59.1625,
    description : 'South America is a continent of incredible natural beauty, characterized by the Amazon Rainforest, the Andes Mountains, and the expansive plains of the Pampas. The continent is known for its cultural diversity, with influences from indigenous peoples, European colonizers, and African slaves shaping its traditions. South America is also famous for its vibrant carnivals and passionate love for football.',
  },
  {
    id : 4,
    name : 'North America',
    lat : 70,
    long : 20.6,
    description : 'North America, a continent of vast contrasts, is home to the United States, Canada, and Mexico. The continent boasts diverse geographical features, including the Rocky Mountains, the Great Plains, and the Arctic tundra. North America has played a crucial role in global politics and economics, with its major cities driving innovation and development.',
  },
  {
    id : 5,
    name : 'Europe',
    lat : 53.8,
    long : 10.5,
    description : 'Europe, with its rich history and cultural heritage, is a continent that has greatly influenced the world. From the Renaissance art of Italy to the Enlightenment philosophy of France, Europe has been a center of intellectual and artistic achievement. The continent is characterized by its diverse landscapes, including the Alps, fjords, and expansive plains, as well as its dynamic mix of languages and cuisines.',
  },
  {
    id : 6,
    name : 'Oceania',
    lat : 37,
    long : 154.5,
    description : "Australia, often referred to as the 'island continent', is known for its unique wildlife, including kangaroos and koalas, as well as its vast deserts and beautiful coastlines. The indigenous Aboriginal culture, with its rich Dreamtime mythology, adds a deep spiritual dimension to Australia's identity. The country's modern cities, such as Sydney and Melbourne, contribute to its status as a global player.",
  },
];