/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Kerem Biçer (https://sketchfab.com/mr.harvester81)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-airplane-08d851cb976742d8bc5eb9424b9cd2fb
Title: Low Poly Airplane
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Airplane(props) {
  const { nodes, materials } = useGLTF('/models/low_poly_airplane/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <group position={[-0.788, -0.004, -0.002]}>
            <mesh geometry={nodes.Cube001_metal_0.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cube001_dark_0.geometry} material={materials.dark} />
          </group>
          <group position={[-0.046, -0.052, 0.001]}>
            <mesh geometry={nodes.Cube002_metal_0.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cube002_dark_0.geometry} material={materials.dark} />
          </group>
          <group position={[-0.046, 0.052, 0.001]}>
            <mesh geometry={nodes.Cube003_metal_0.geometry} material={materials.metal} />
            <mesh geometry={nodes.Cube003_dark_0.geometry} material={materials.dark} />
          </group>
          <mesh geometry={nodes.Cube_blue_0.geometry} material={materials.blue} />
          <mesh geometry={nodes.Cube_white_0.geometry} material={materials.white} />
          <mesh geometry={nodes.Cube_dark_0.geometry} material={materials.dark} />
          <mesh geometry={nodes.Cube_metal_0.geometry} material={materials.metal} />
          <mesh geometry={nodes.Cube_window_0.geometry} material={materials.window} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/low_poly_airplane/scene.gltf')
