/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: stokicdizajn (https://sketchfab.com/stokicdizajn)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/stylized-crate-asset-fe35790843334e5e87889002d7f69dc4
Title: Stylized Crate Asset
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Box(props) {
  const { nodes, materials } = useGLTF('/models/box/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Kutija_low_drvo_0.geometry} material={materials.drvo} position={[0, 111.176, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Metal_low_metal_0.geometry} material={materials.metal} position={[0, 110.691, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[99.651, 99.651, 99.879]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/box/scene.gltf')
