/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Roman_Nilikovskii (https://sketchfab.com/Roman_Nilikovskii)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cat-house-3ccdeded08134525acfa5b59a734a6d3
Title: Cat House
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CatHouse(props) {
  const { nodes, materials } = useGLTF('/models/cat_house/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Cube018_Material001_0.geometry} material={materials['Material.001']} position={[0, 58.498, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cube001_Material002_0.geometry} material={materials['Material.002']} position={[0, 58.498, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/cat_house/scene.gltf')
