/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: tprevis (https://sketchfab.com/tprevis)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/door-36-inch-15jan24-1b141992d7434a968f85b3dd28d96ebf
Title: Door 36 Inch 15JAN24
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Door(props) {
  const { nodes, materials } = useGLTF('/models/door/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <lineSegments geometry={nodes.Material4.geometry} material={materials.edge_color24714660255} />
        <mesh geometry={nodes.Material2.geometry} material={materials.lighter_bamboo} />
        <mesh geometry={nodes.Material2_1.geometry} material={materials.Color_F01} />
        <lineSegments geometry={nodes.Material4_1.geometry} material={materials.edge_color193193193255} />
        <mesh geometry={nodes.Material3.geometry} material={materials.Metal_Corrogated_Shiny_1} />
        <lineSegments geometry={nodes.Material4_2.geometry} material={materials.edge_color177105430} />
        <mesh geometry={nodes.Material2_2.geometry} material={materials['36_WHT_4090470']} />
        <mesh geometry={nodes.Material2_3.geometry} material={materials.Wood_Bamboo_Medium} />
        <lineSegments geometry={nodes.Material3_1.geometry} material={materials.edge_color2022092190} />
        <mesh geometry={nodes.Material2_4.geometry} material={materials.Metal_Aluminum_Anodized_3} />
        <mesh geometry={nodes.Material2_5.geometry} material={materials.Metal_Corrogated_Shiny_2} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/door/scene.gltf')
