/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: GuluBuddy (https://sketchfab.com/GuluBuddy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/isabelle-a0d601d684d940f5bb4f71f42c02f0b6
Title: Isabelle
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Isabelle(props) {
  const { nodes, materials } = useGLTF('/models/isabelle/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.color_12568524} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.color_15245924} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.color_15277357} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color_16448250} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.color_16748194} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.color_16748194} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.color_16761662} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.color_16764116} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.color_16764116} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.color_16764116} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.color_16771245} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.color_16775918} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.color_2829873} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.color_6303507} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.color_6383466} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.color_9458488} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/isabelle/scene.gltf')
