/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Konek (https://sketchfab.com/K0nek)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/freddy-fazbear-minecraft-c5e32c02c2434a9a8a4413aa94deacfd
Title: Freddy Fazbear Minecraft
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function NPC(props) {
  const { nodes, materials } = useGLTF('/models/NPC/scene.gltf')
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.571, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.019, 0, 0]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_14.geometry} material={materials.material_0} />
          </group>
          <group position={[0.016, 0, 0]}>
            <mesh geometry={nodes.Object_17.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_19.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_21.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_23.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_25.geometry} material={materials.material_0} />
          </group>
          <group position={[0.25, 0.719, 0]}>
            <group position={[-0.375, -0.688, 0.063]}>
              <mesh geometry={nodes.Object_41.geometry} material={materials.material_0} position={[0, 0.087, 0]} />
              <mesh geometry={nodes.Object_43.geometry} material={materials.material_0} position={[0, 0.087, 0]} />
              <mesh geometry={nodes.Object_45.geometry} material={materials.material_0} position={[0, 0.087, 0]} />
              <mesh geometry={nodes.Object_47.geometry} material={materials.material_0} position={[0, 0.087, 0]} />
              <mesh geometry={nodes.Object_49.geometry} material={materials.material_0} position={[0, 0.087, 0]} />
            </group>
            <mesh geometry={nodes.Object_28.geometry} material={materials.material_0} position={[0, 0.025, 0]} />
            <mesh geometry={nodes.Object_30.geometry} material={materials.material_0} position={[0, 0.025, 0]} />
            <mesh geometry={nodes.Object_32.geometry} material={materials.material_0} position={[0, 0.087, 0]} />
            <mesh geometry={nodes.Object_34.geometry} material={materials.material_0} position={[0, 0.025, 0]} />
            <mesh geometry={nodes.Object_36.geometry} material={materials.material_0} position={[0, 1.087, 0]} rotation={[0, 0, -0.175]} />
            <mesh geometry={nodes.Object_38.geometry} material={materials.material_0} position={[0, 1.087, 0]} rotation={[0, 0, -0.175]} />
          </group>
          <group position={[-0.438, 0.719, 0]}>
            <group position={[-0.375, -0.688, 0.063]}>
              <mesh geometry={nodes.Object_65.geometry} material={materials.material_0} position={[0, 0.087, 0]} />
              <mesh geometry={nodes.Object_67.geometry} material={materials.material_0} position={[0, 0.087, 0]} />
              <mesh geometry={nodes.Object_69.geometry} material={materials.material_0} position={[0, 0.087, 0]} />
              <mesh geometry={nodes.Object_71.geometry} material={materials.material_0} position={[0, 0.087, 0]} />
              <mesh geometry={nodes.Object_73.geometry} material={materials.material_0} position={[0, 0.087, 0]} />
            </group>
            <mesh geometry={nodes.Object_52.geometry} material={materials.material_0} position={[0, 0.025, 0]} />
            <mesh geometry={nodes.Object_54.geometry} material={materials.material_0} position={[0, 0.025, 0]} />
            <mesh geometry={nodes.Object_56.geometry} material={materials.material_0} position={[0, 0.025, 0]} />
            <mesh geometry={nodes.Object_58.geometry} material={materials.material_0} position={[0, 0.087, 0]} />
            <mesh geometry={nodes.Object_60.geometry} material={materials.material_0} position={[0, 1.087, 0]} rotation={[0, 0, 0.175]} />
            <mesh geometry={nodes.Object_62.geometry} material={materials.material_0} position={[0, 1.087, 0]} rotation={[0, 0, 0.175]} />
          </group>
          <group position={[0, 0, 0.063]}>
            <mesh geometry={nodes.Object_88.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_90.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.Object_92.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.Object_94.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.Object_96.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.Object_99.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.Object_101.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.Object_103.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.Object_105.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.Object_107.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.Object_109.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.Object_111.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.Object_113.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.Object_115.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.Object_117.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.Object_119.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <mesh geometry={nodes.Object_121.geometry} material={materials.material_0} position={[0, -0.05, 0]} />
            <group position={[0, -0.05, 0]}>
              <group position={[0, 0.05, 0]}>
                <mesh geometry={nodes.Object_145.geometry} material={materials.material_0} rotation={[0, 0, -Math.PI / 4]} />
                <mesh geometry={nodes.Object_147.geometry} material={materials.material_0} rotation={[0, 0, -Math.PI / 4]} />
              </group>
              <group position={[-2.203, 2.269, 0]} rotation={[0, 0, -Math.PI / 2]}>
                <mesh geometry={nodes.Object_150.geometry} material={materials.material_0} rotation={[0, 0, -Math.PI / 4]} />
                <mesh geometry={nodes.Object_152.geometry} material={materials.material_0} rotation={[0, 0, -Math.PI / 4]} />
              </group>
              <group position={[0, 0.05, -0.063]}>
                <mesh geometry={nodes.Object_155.geometry} material={materials.material_0} />
                <mesh geometry={nodes.Object_157.geometry} material={materials.material_0} />
              </group>
              <mesh geometry={nodes.Object_126.geometry} material={materials.material_0} />
              <mesh geometry={nodes.Object_128.geometry} material={materials.material_0} />
              <mesh geometry={nodes.Object_130.geometry} material={materials.material_0} />
              <mesh geometry={nodes.Object_132.geometry} material={materials.material_0} />
              <mesh geometry={nodes.Object_134.geometry} material={materials.material_0} />
              <mesh geometry={nodes.Object_136.geometry} material={materials.material_0} />
              <mesh geometry={nodes.Object_138.geometry} material={materials.material_0} />
              <mesh geometry={nodes.Object_140.geometry} material={materials.material_0} position={[0, 0.05, 0.038]} rotation={[0, 0, 0.175]} />
              <mesh geometry={nodes.Object_142.geometry} material={materials.material_0} position={[0, 0.05, 0.038]} rotation={[0, 0, -0.175]} />
            </group>
            <group position={[0, -0.05, 0]}>
              <mesh geometry={nodes.Object_169.geometry} material={materials.material_0} />
              <mesh geometry={nodes.Object_171.geometry} material={materials.material_0} />
              <mesh geometry={nodes.Object_173.geometry} material={materials.material_0} position={[0, 0.05, 0]} />
            </group>
            <mesh geometry={nodes.Object_160.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_162.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_164.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_166.geometry} material={materials.material_0} />
          </group>
          <mesh geometry={nodes.Object_76.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_78.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_80.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_82.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_84.geometry} material={materials.material_0} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/NPC/scene.gltf')
