/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: WillowBoxArt (https://sketchfab.com/willowboxart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-house-7a709f33bf724062b0caf308c0c81e71
Title: Stylized House
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function StylizedHouse(props) {
  const { nodes, materials } = useGLTF('/models/stylized_house/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.SM_Stylized_House_M_Glass_0.geometry} material={materials.M_Glass} />
        <mesh geometry={nodes.SM_Stylized_House_M_house_0.geometry} material={materials.M_house} />
        <mesh geometry={nodes.SM_Stylized_House_M_Roof_0.geometry} material={materials.M_Roof} />
        <mesh geometry={nodes.SM_Stylized_House_M_Window_Frame_0.geometry} material={materials.M_Window_Frame} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/stylized_house/scene.gltf')
