/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Anike0097 (https://sketchfab.com/Anike0097)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-tree-house-b0395ed9fe2f480e80ee5913cc9bf0f8
Title: LOW POLY TREE HOUSE
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TreeHouse(props) {
  const { nodes, materials } = useGLTF('/models/low_poly_tree_house/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, -8.807, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[83.356, 83.356, 53.335]}>
          <mesh geometry={nodes.Vert_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Vert_Material001_0_1.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Vert_Material001_0_2.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Icosphere_Material012_0.geometry} material={materials['Material.012']} position={[0.134, 0.918, 3.25]} scale={[0.394, 0.26, 0.406]} />
          <mesh geometry={nodes.Icosphere005_Material012_0.geometry} material={materials['Material.012']} position={[0.509, -1.373, 4.58]} scale={[0.558, 0.368, 0.575]} />
          <mesh geometry={nodes.Icosphere011_Material012_0.geometry} material={materials['Material.012']} position={[-0.498, -1.749, 4.332]} scale={[0.684, 0.451, 0.705]} />
          <mesh geometry={nodes.Icosphere012_Material012_0.geometry} material={materials['Material.012']} position={[-0.039, -1.034, 4.28]} scale={[0.558, 0.368, 0.575]} />
          <mesh geometry={nodes.Icosphere014_Material012_0.geometry} material={materials['Material.012']} position={[-0.039, -1.034, 4.28]} scale={[0.558, 0.368, 0.575]} />
          <mesh geometry={nodes.Icosphere018_Material012_0.geometry} material={materials['Material.012']} position={[-1.202, 0.224, 4.591]} scale={[0.684, 0.451, 0.705]} />
          <mesh geometry={nodes.Icosphere022_Material012_0.geometry} material={materials['Material.012']} position={[-1.108, 1.156, 3.182]} scale={[0.43, 0.284, 0.444]} />
          <mesh geometry={nodes.Icosphere026_Material012_0.geometry} material={materials['Material.012']} position={[-1.182, 0.909, 4.007]} scale={[0.447, 0.295, 0.461]} />
          <mesh geometry={nodes.Icosphere001_Material012_0.geometry} material={materials['Material.012']} position={[0.566, -0.285, 4.796]} scale={[0.795, 0.524, 0.82]} />
        </group>
        <group position={[1.554, 173.329, -13.097]} rotation={[Math.PI, 0, 0]} scale={[-6.157, 3.548, 6.905]}>
          <mesh geometry={nodes.Cube022_Material_0.geometry} material={materials.Material} />
          <mesh geometry={nodes.Cube022_Material006_0.geometry} material={materials['Material.006']} />
        </group>
        <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} position={[8.455, 116.544, 2.169]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={36.358} />
        <mesh geometry={nodes.Cube001_Material002_0.geometry} material={materials['Material.002']} position={[27.628, 119.151, -32.912]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={1.949} />
        <mesh geometry={nodes.Cube002_Material_0.geometry} material={materials.Material} position={[29.127, 166.045, 23.088]} rotation={[-0.855, 0, -Math.PI]} scale={[3.644, 27.995, 0.366]} />
        <mesh geometry={nodes.Cube003_Material_0.geometry} material={materials.Material} position={[29.68, 166.234, -19.131]} rotation={[0.856, 0, Math.PI]} scale={[3.644, 27.995, 0.366]} />
        <mesh geometry={nodes.Cube004_Material002_0.geometry} material={materials['Material.002']} position={[0.917, 183.354, 2.169]} rotation={[-2.356, 0, -Math.PI]} scale={[36.165, 2.47, 2.47]} />
        <mesh geometry={nodes.Cube005_Material002_0.geometry} material={materials['Material.002']} position={[-26.382, 119.151, -32.912]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={1.949} />
        <mesh geometry={nodes.Cube006_Material002_0.geometry} material={materials['Material.002']} position={[27.628, 119.151, 36.943]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={1.949} />
        <mesh geometry={nodes.Cube007_Material002_0.geometry} material={materials['Material.002']} position={[-26.34, 119.151, 36.943]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={1.949} />
        <mesh geometry={nodes.Cube009_Material_0.geometry} material={materials.Material} position={[22.369, 133.811, 38.407]} rotation={[Math.PI, 0, Math.PI]} scale={[2.812, 16.456, 0.282]} />
        <mesh geometry={nodes.Cube008_Material_0.geometry} material={materials.Material} position={[22.369, 133.811, -34.57]} rotation={[Math.PI, 0, Math.PI]} scale={[2.812, 16.456, 0.282]} />
        <mesh geometry={nodes.Cube010_Material_0.geometry} material={materials.Material} position={[-28.238, 135.626, 32.315]} rotation={[0, Math.PI / 2, 0]} scale={[3.112, 18.211, 0.313]} />
        <mesh geometry={nodes.Cube012_Material006_0.geometry} material={materials['Material.006']} position={[27.313, 162.44, 2.167]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1.887, 7.797, 10.573]} />
        <mesh geometry={nodes.Cube013_Material002_0.geometry} material={materials['Material.002']} position={[29.037, 162.44, 2.167]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.615, 0.652, 10.632]} />
        <mesh geometry={nodes.Cube014_Material002_0.geometry} material={materials['Material.002']} position={[28.406, 173.038, 2.167]} rotation={[Math.PI, 0, 0]} scale={[-0.615, 0.652, 9.323]} />
        <mesh geometry={nodes.Cube015_Material002_0.geometry} material={materials['Material.002']} position={[29.014, 166.288, 2.167]} rotation={[Math.PI, 0, 0]} scale={[-0.615, 0.652, 7.849]} />
        <mesh geometry={nodes.Cube016_Material002_0.geometry} material={materials['Material.002']} position={[29.014, 158.904, 2.167]} rotation={[Math.PI, 0, 0]} scale={[-0.615, 0.652, 7.849]} />
        <mesh geometry={nodes.Cube017_Material002_0.geometry} material={materials['Material.002']} position={[29.425, 162.44, 9.569]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.666, 0.843, 10.585]} />
        <mesh geometry={nodes.Cube018_Material002_0.geometry} material={materials['Material.002']} position={[29.425, 162.44, -5.28]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.666, 0.843, 10.585]} />
        <mesh geometry={nodes.Cube011_Material_0.geometry} material={materials.Material} position={[1.554, 169.297, -13.715]} rotation={[Math.PI, 0, 0]} scale={[-7.14, 0.588, 6.905]} />
        <mesh geometry={nodes.Cube019_Material_0.geometry} material={materials.Material} position={[8.055, 172.917, -13.715]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-4.083, 0.588, 6.905]} />
        <mesh geometry={nodes.Cube020_Material_0.geometry} material={materials.Material} position={[-4.94, 172.917, -13.715]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={[-4.083, 0.588, 6.905]} />
        <mesh geometry={nodes.Cube021_Material004_0.geometry} material={materials['Material.004']} position={[1.554, 177.359, -13.715]} rotation={[Math.PI, 0, 0]} scale={[-7.14, 0.588, 6.905]} />
        <mesh geometry={nodes.Cube023_Material002_0.geometry} material={materials['Material.002']} position={[7.92, 178.494, -19.096]} rotation={[-3.14, 0.057, -2.48]} scale={[-2.582, 0.31, 2.222]} />
        <mesh geometry={nodes.Cube024_Material002_0.geometry} material={materials['Material.002']} position={[3.69, 181.797, -19.331]} rotation={[-3.14, 0.057, -2.48]} scale={[-2.292, 0.275, 1.972]} />
        <mesh geometry={nodes.Cube025_Material002_0.geometry} material={materials['Material.002']} position={[7.645, 178.486, -14.261]} rotation={[-3.14, 0.057, -2.48]} scale={[-2.582, 0.31, 2.222]} />
        <mesh geometry={nodes.Cube026_Material002_0.geometry} material={materials['Material.002']} position={[3.415, 181.789, -14.496]} rotation={[-3.14, 0.057, -2.48]} scale={[-2.292, 0.275, 1.972]} />
        <mesh geometry={nodes.Cube027_Material002_0.geometry} material={materials['Material.002']} position={[7.92, 178.494, -9.024]} rotation={[-3.14, 0.057, -2.48]} scale={[-2.582, 0.31, 2.222]} />
        <mesh geometry={nodes.Cube028_Material002_0.geometry} material={materials['Material.002']} position={[3.69, 181.797, -9.259]} rotation={[-3.14, 0.057, -2.48]} scale={[-2.292, 0.275, 1.972]} />
        <mesh geometry={nodes.Cube029_Material002_0.geometry} material={materials['Material.002']} position={[-4.853, 178.665, -19.264]} rotation={[3.085, -0.005, -0.756]} scale={[-2.582, 0.31, 2.222]} />
        <mesh geometry={nodes.Cube030_Material002_0.geometry} material={materials['Material.002']} position={[-0.441, 181.811, -19.467]} rotation={[3.085, -0.005, -0.756]} scale={[-2.292, 0.275, 1.972]} />
        <mesh geometry={nodes.Cube031_Material002_0.geometry} material={materials['Material.002']} position={[-4.615, 178.757, -13.328]} rotation={[3.085, -0.005, -0.7]} scale={[-2.582, 0.31, 2.222]} />
        <mesh geometry={nodes.Cube032_Material002_0.geometry} material={materials['Material.002']} position={[-0.646, 181.898, -13.528]} rotation={[3.085, -0.005, -0.686]} scale={[-2.292, 0.275, 1.972]} />
        <mesh geometry={nodes.Cube033_Material002_0.geometry} material={materials['Material.002']} position={[-4.713, 178.57, -8.096]} rotation={[3.085, -0.005, -0.756]} scale={[-2.582, 0.31, 2.222]} />
        <mesh geometry={nodes.Cube034_Material002_0.geometry} material={materials['Material.002']} position={[-0.475, 181.9, -8.308]} rotation={[3.085, -0.005, -0.756]} scale={[-2.292, 0.275, 1.972]} />
        <mesh geometry={nodes.Cube035_Material003_0.geometry} material={materials['Material.003']} position={[15.867, 116.835, -64.019]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[56.848, 3.985, 0.641]} />
        <mesh geometry={nodes.Cube041_Material003_0.geometry} material={materials['Material.003']} position={[67.151, 131.889, 7.575]} rotation={[Math.PI, 0, Math.PI]} scale={[1.178, 1.178, 51.091]} />
        <mesh geometry={nodes.Cube042_Material003_0.geometry} material={materials['Material.003']} position={[-35.784, 131.889, -2.457]} rotation={[Math.PI, 0, Math.PI]} scale={[1.178, 1.178, 62.395]} />
        <mesh geometry={nodes.Cube043_Material003_0.geometry} material={materials['Material.003']} position={[15.648, 131.889, -63.761]} rotation={[0, -Math.PI / 2, 0]} scale={[1.178, 1.178, 49.675]} />
        <mesh geometry={nodes.Cube044_Material003_0.geometry} material={materials['Material.003']} position={[15.648, 131.889, 59.785]} rotation={[0, -Math.PI / 2, 0]} scale={[1.178, 1.178, 49.675]} />
        <mesh geometry={nodes.Cube045_Material013_0.geometry} material={materials['Material.013']} position={[67.151, 124.372, -37.683]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.467, 0.467, 6.443]} />
        <mesh geometry={nodes.Cube046_Material013_0.geometry} material={materials['Material.013']} position={[-35.862, 124.372, -60.804]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.467, 0.467, 6.443]} />
        <mesh geometry={nodes.Cube047_Material013_0.geometry} material={materials['Material.013']} position={[63.157, 124.372, -63.68]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.467, 0.467, 6.443]} />
        <mesh geometry={nodes.Cube048_Material013_0.geometry} material={materials['Material.013']} position={[63.157, 124.372, 59.976]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.467, 0.467, 6.443]} />
        <mesh geometry={nodes.Cylinder001_Material003_0.geometry} material={materials['Material.003']} position={[67.206, 125.998, -43.193]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.957, 1.957, 8.872]} />
        <mesh geometry={nodes.Cylinder003_Material003_0.geometry} material={materials['Material.003']} position={[66.512, 125.998, -63.702]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.957, 1.957, 8.872]} />
        <mesh geometry={nodes.Cylinder004_Material003_0.geometry} material={materials['Material.003']} position={[66.604, 125.998, 59.644]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.957, 1.957, 8.872]} />
        <mesh geometry={nodes.Cylinder002_Material003_0.geometry} material={materials['Material.003']} position={[-35.775, 125.998, 59.644]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.957, 1.957, 8.872]} />
        <mesh geometry={nodes.Cylinder005_Material003_0.geometry} material={materials['Material.003']} position={[-35.775, 125.998, -64.372]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.957, 1.957, 8.872]} />
        <mesh geometry={nodes.Cube036_Material003_0.geometry} material={materials['Material.003']} position={[32.946, 84.139, -64.019]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[80.459, 3.985, 0.641]} />
        <mesh geometry={nodes.Cube037_Material003_0.geometry} material={materials['Material.003']} position={[108.06, 99.391, 7.575]} rotation={[Math.PI, 0, Math.PI]} scale={[1.178, 1.178, 51.091]} />
        <mesh geometry={nodes.Cube038_Material003_0.geometry} material={materials['Material.003']} position={[-35.784, 99.391, -2.457]} rotation={[Math.PI, 0, Math.PI]} scale={[1.178, 1.178, 62.395]} />
        <mesh geometry={nodes.Cube039_Material003_0.geometry} material={materials['Material.003']} position={[36.246, 99.391, -64.581]} rotation={[0, -Math.PI / 2, 0]} scale={[1.178, 1.178, 73.086]} />
        <mesh geometry={nodes.Cube040_Material003_0.geometry} material={materials['Material.003']} position={[36.1, 99.391, 59.785]} rotation={[0, -Math.PI / 2, 0]} scale={[1.178, 1.178, 70.588]} />
        <mesh geometry={nodes.Cube049_Material013_0.geometry} material={materials['Material.013']} position={[108.046, 91.874, -37.683]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.467, 0.467, 6.443]} />
        <mesh geometry={nodes.Cube050_Material013_0.geometry} material={materials['Material.013']} position={[-35.862, 91.874, -60.804]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.467, 0.467, 6.443]} />
        <mesh geometry={nodes.Cube051_Material013_0.geometry} material={materials['Material.013']} position={[106.794, 91.874, -64.499]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.467, 0.467, 6.443]} />
        <mesh geometry={nodes.Cube052_Material013_0.geometry} material={materials['Material.013']} position={[107.762, 91.874, 59.976]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.467, 0.467, 6.443]} />
        <mesh geometry={nodes.Cylinder006_Material003_0.geometry} material={materials['Material.003']} position={[108.103, 93.5, -43.193]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.957, 1.957, 8.872]} />
        <mesh geometry={nodes.Cylinder007_Material003_0.geometry} material={materials['Material.003']} position={[108.054, 93.5, -64.772]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.957, 1.957, 8.872]} />
        <mesh geometry={nodes.Cylinder008_Material003_0.geometry} material={materials['Material.003']} position={[108.121, 93.5, 59.644]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.957, 1.957, 8.872]} />
        <mesh geometry={nodes.Cylinder009_Material003_0.geometry} material={materials['Material.003']} position={[-35.775, 93.5, 59.644]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.957, 1.957, 8.872]} />
        <mesh geometry={nodes.Cylinder010_Material003_0.geometry} material={materials['Material.003']} position={[-35.775, 93.5, -65.192]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.957, 1.957, 8.872]} />
        <mesh geometry={nodes.Cube053_Material003_0.geometry} material={materials['Material.003']} position={[86.639, 105.403, -63.994]} rotation={[-Math.PI / 2, -Math.PI / 4, 0]} scale={[2.003, 0.693, 27.515]} />
        <mesh geometry={nodes.Cube054_Material003_0.geometry} material={materials['Material.003']} position={[86.639, 105.403, -43.5]} rotation={[-Math.PI / 2, -Math.PI / 4, 0]} scale={[2.003, 0.693, 27.515]} />
        <mesh geometry={nodes.Cube055_Material003_0.geometry} material={materials['Material.003']} position={[102.901, 88.354, -53.999]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-4.506, 9.259, 0.672]} />
        <mesh geometry={nodes.Cube056_Material003_0.geometry} material={materials['Material.003']} position={[97.944, 95.443, -53.999]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-4.506, 9.259, 0.672]} />
        <mesh geometry={nodes.Cube057_Material003_0.geometry} material={materials['Material.003']} position={[91.959, 102.48, -53.999]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-4.506, 9.259, 0.672]} />
        <mesh geometry={nodes.Cube061_Material003_0.geometry} material={materials['Material.003']} position={[84.393, 108.478, -53.999]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-4.506, 9.259, 0.672]} />
        <mesh geometry={nodes.Cube062_Material003_0.geometry} material={materials['Material.003']} position={[77.755, 114.068, -53.999]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-4.506, 9.259, 0.672]} />
        <mesh geometry={nodes.Cylinder011_Material003_0.geometry} material={materials['Material.003']} position={[124.937, 35.619, -64.522]} rotation={[-Math.PI / 2, -0.274, 0]} scale={[1.086, 1.086, 50.017]} />
        <mesh geometry={nodes.Cylinder012_Material003_0.geometry} material={materials['Material.003']} position={[124.883, 35.815, -43.784]} rotation={[-Math.PI / 2, -0.274, 0]} scale={[1.086, 1.086, 50.017]} />
        <mesh geometry={nodes.Cylinder013_Material003_0.geometry} material={materials['Material.003']} position={[135.366, -1.525, -54.073]} rotation={[Math.PI, 0, -0.274]} scale={[0.88, 0.88, 10.535]} />
        <mesh geometry={nodes.Cube060_Material003_0.geometry} material={materials['Material.003']} position={[97.788, 95.495, -53.999]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-4.506, 9.259, 0.672]} />
        <mesh geometry={nodes.Cube059_Material003_0.geometry} material={materials['Material.003']} position={[102.885, 88.366, -53.999]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-4.506, 9.259, 0.672]} />
        <mesh geometry={nodes.Cylinder_Material014_0.geometry} material={materials['Material.014']} position={[0, -17.165, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[155.402, 155.402, 8.054]} />
        <mesh geometry={nodes.Icosphere002_Material015_0.geometry} material={materials['Material.015']} position={[-10.435, -8.757, -30.606]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.26, 10.726, 10.726]} />
        <mesh geometry={nodes.Icosphere003_Material015_0.geometry} material={materials['Material.015']} position={[6.507, -8.757, -27.733]} rotation={[2.103, -0.302, -1.704]} scale={[16.26, 10.726, 10.726]} />
        <mesh geometry={nodes.Icosphere004_Material015_0.geometry} material={materials['Material.015']} position={[29.427, -9.2, -30.606]} rotation={[-Math.PI / 2, 0, 0]} scale={[6.588, 4.346, 4.346]} />
        <mesh geometry={nodes.Icosphere006_Material015_0.geometry} material={materials['Material.015']} position={[29.427, -9.2, -0.545]} rotation={[-0.828, 0.363, -0.125]} scale={[5.255, 3.466, 3.466]} />
        <mesh geometry={nodes.Icosphere007_Material015_0.geometry} material={materials['Material.015']} position={[28.991, -9.2, -16.498]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.79, 11.075, 11.075]} />
        <mesh geometry={nodes.Icosphere008_Material015_0.geometry} material={materials['Material.015']} position={[27.989, -7.477, 19.908]} rotation={[-0.669, -0.086, 0.185]} scale={[16.79, 11.075, 11.075]} />
        <mesh geometry={nodes.Icosphere009_Material015_0.geometry} material={materials['Material.015']} position={[8.336, -7.477, 31.109]} rotation={[0.371, 0.01, 1.055]} scale={[9.894, 6.526, 6.526]} />
        <mesh geometry={nodes.Icosphere010_Material015_0.geometry} material={materials['Material.015']} position={[-7.078, -7.477, 31.109]} rotation={[-1.025, 0.211, -2.125]} scale={[15.393, 10.154, 10.154]} />
        <mesh geometry={nodes.Icosphere013_Material015_0.geometry} material={materials['Material.015']} position={[18.516, -7.477, 46.217]} rotation={[-0.173, -0.129, -1.338]} scale={[11.565, 7.629, 7.629]} />
        <mesh geometry={nodes.Icosphere015_Material015_0.geometry} material={materials['Material.015']} position={[-29.415, -7.477, 22.154]} rotation={[-0.66, -0.882, -0.67]} scale={[10.473, 6.909, 6.909]} />
        <mesh geometry={nodes.Icosphere016_Material015_0.geometry} material={materials['Material.015']} position={[2.064, -10.088, 44.97]} rotation={[-0.29, -0.019, 0.189]} scale={[11.565, 7.629, 7.629]} />
        <mesh geometry={nodes.Icosphere017_Material015_0.geometry} material={materials['Material.015']} position={[-29.415, -8.585, -5.712]} rotation={[-0.66, -0.882, -0.67]} scale={[10.473, 6.909, 6.909]} />
        <mesh geometry={nodes.Cube058_Material002_0.geometry} material={materials['Material.002']} position={[3.69, 181.797, -4.822]} rotation={[-3.14, 0.057, -2.48]} scale={[-2.292, 0.275, 1.972]} />
        <mesh geometry={nodes.Cube063_Material002_0.geometry} material={materials['Material.002']} position={[-0.475, 181.9, -3.56]} rotation={[3.085, -0.005, -0.756]} scale={[-2.292, 0.275, 1.972]} />
        <mesh geometry={nodes.Cube065_Material002_0.geometry} material={materials['Material.002']} position={[29.014, 152.431, 2.167]} rotation={[Math.PI, 0, 0]} scale={[-0.615, 0.652, 7.849]} />
        <mesh geometry={nodes.Circle_Material001_0.geometry} material={materials['Material.001']} position={[29.308, 134.923, 0.007]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
        <mesh geometry={nodes.Cube064_Material002_0.geometry} material={materials['Material.002']} position={[31.237, 121.973, 6.353]} rotation={[3.098, 0.036, -1.563]} scale={[-1.15, 0.31, 1.885]} />
        <mesh geometry={nodes.Cube066_Material002_0.geometry} material={materials['Material.002']} position={[31.038, 125.652, 6.763]} rotation={[3.098, 0.036, -1.563]} scale={[-1.15, 0.31, 1.885]} />
        <mesh geometry={nodes.Cube067_Material002_0.geometry} material={materials['Material.002']} position={[30.842, 129.132, 6.365]} rotation={[3.098, 0.036, -1.563]} scale={[-1.15, 0.31, 1.885]} />
        <mesh geometry={nodes.Cube068_Material002_0.geometry} material={materials['Material.002']} position={[30.842, 133, 6.365]} rotation={[3.098, 0.036, -1.563]} scale={[-1.15, 0.31, 1.885]} />
        <mesh geometry={nodes.Cube069_Material002_0.geometry} material={materials['Material.002']} position={[30.842, 136.548, 5.259]} rotation={[3.098, 0.036, -1.563]} scale={[-1.15, 0.31, 1.885]} />
        <mesh geometry={nodes.Cube070_Material002_0.geometry} material={materials['Material.002']} position={[30.842, 139.373, 3.431]} rotation={[3.098, 0.036, -1.563]} scale={[-1.15, 0.31, 1.885]} />
        <mesh geometry={nodes.Cube071_Material002_0.geometry} material={materials['Material.002']} position={[30.842, 140.265, -0.771]} rotation={[3.098, 0.036, -1.563]} scale={[-1.15, 0.31, 1.885]} />
        <mesh geometry={nodes.Cube072_Material002_0.geometry} material={materials['Material.002']} position={[30.842, 138.806, -4.839]} rotation={[3.098, 0.036, -1.563]} scale={[-1.15, 0.31, 1.885]} />
        <mesh geometry={nodes.Cube073_Material002_0.geometry} material={materials['Material.002']} position={[30.842, 135.549, -7.029]} rotation={[3.098, 0.036, -1.563]} scale={[-1.15, 0.31, 1.885]} />
        <mesh geometry={nodes.Cube074_Material002_0.geometry} material={materials['Material.002']} position={[31.322, 121.426, -6.177]} rotation={[3.098, 0.036, -1.563]} scale={[-1.15, 0.31, 1.885]} />
        <mesh geometry={nodes.Cube075_Material002_0.geometry} material={materials['Material.002']} position={[31.127, 125.105, -6.528]} rotation={[3.098, 0.036, -1.563]} scale={[-1.15, 0.31, 1.885]} />
        <mesh geometry={nodes.Cube076_Material002_0.geometry} material={materials['Material.002']} position={[31.038, 128.585, -6.596]} rotation={[3.098, 0.036, -1.563]} scale={[-1.15, 0.31, 1.885]} />
        <mesh geometry={nodes.Cube077_Material002_0.geometry} material={materials['Material.002']} position={[30.98, 132.186, -6.709]} rotation={[3.098, 0.036, -1.563]} scale={[-1.15, 0.31, 1.885]} />
        <mesh geometry={nodes.Cube078_Material006_0.geometry} material={materials['Material.006']} position={[30.885, 128.3, -6.641]} rotation={[1.527, 0.036, -1.563]} scale={[-1.181, 0.316, 10.848]} />
        <mesh geometry={nodes.Cube079_Material015_0.geometry} material={materials['Material.015']} position={[31.283, 128.233, 2.707]} rotation={[0, 0, Math.PI]} scale={[-0.328, 0.674, 0.049]} />
        <mesh geometry={nodes.Torus_Material007_0.geometry} material={materials['Material.007']} position={[31.247, 127.437, 2.465]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.583} />
        <mesh geometry={nodes.Cube080_Material002_0.geometry} material={materials['Material.002']} position={[31.689, 118.549, 6.776]} rotation={[3.098, 0.036, -1.563]} scale={[-1.15, 0.31, 1.885]} />
        <mesh geometry={nodes.Cube081_Material002_0.geometry} material={materials['Material.002']} position={[31.774, 118.002, -6.017]} rotation={[3.098, 0.036, -1.563]} scale={[-1.15, 0.31, 1.885]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/low_poly_tree_house/scene.gltf')
